basePath: /api/proxy_crud/v1
host: localhost:10000
info:
  contact: {}
  description: CRUD.
  title: Proxy Crud Service
  version: "1.0"
paths:
  /heartbeat:
    get:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      summary: Heartbeat metric
      tags:
      - Metrics
swagger: "2.0"
